### ISSUE TITLE
Arquivos Moh

### ISSUE THREAD

**Issue by Filipe-Mariano** [DialplanReload/backup-snep#1]
Olá, usei esse processo, exportei de uma máquina física e importei em uma VM, funcionou perfeitamente com 2 poréns;

1) Na questão do áudio, os arquivos dentro de pastas em Moh não foram copiados.
2) Os troncos importados, vieram com configuração de autenticação habilitadas, no original algumas estavam pra ficar sem autenticação.

Demais tudo 100%.

**Comment by afreitasdotdev** [comment]
E ai, Filipe

Tranquilo?

Dei uma checada nisso, os arquivos do moh realmente não vão, pois estou salvando somente o "sounds", Mas vou abrir uma issue pra essa funcionalidade.

Referente aos troncos, o script não faz nenhuma intervenção nas configurações. Nao tive problemas em laboratório :(
